### ISSUE TITLE
Compilation error on React

### ISSUE THREAD

**Issue by keltjw** [hassanshuja/vet-help#1]
Steps to recreate error:
from vet-help/mern/react:
$npm install
$npm start
```
Failed to compile.

./src/Routes.js
Attempted import error: 'Route' is not exported from 'react-router-dom'.
```
Checked in node_modules that react-router-dom and react-router are both installed at version 5.0.0.

When trying a quick fix test and importing from react-router directly, 'withRouter' subsequently fails to import too.

https://github.com/ReactTraining/react-router/issues/6639
Suggests version incompatibility.

**Comment by hassanshuja** [comment]
can you please remove node_modules and composer-lock.json and run npm install again as we have no issues on compiling the project.

**Comment by keltjw** [comment]
a clean reinstall after installing yarn globally fixed the issue
